// src/api/dummy/board_dummy.ts

import type {
  BoardContent,
  BoardComment,
  BoardCategory,
  BoardTag,
} from "../../screens/board/BoardList";

function makeComment(
  id: number,
  author: string,
  content: string,
  anonymity?: boolean
): BoardComment {
  return {
    id,
    author,
    contents: content,
    anonymity: anonymity ?? false,
    create_time: new Date().toISOString(),
  };
}
export const TAGS: Record<number, BoardTag> = {
  1: { id: 1, name: "일상" },
  2: { id: 2, name: "강의" },
  3: { id: 3, name: "홍보" },
  4: { id: 4, name: "오타" },
};

export const BOARD_DUMMY: Record<BoardCategory, BoardContent[]> = {
  daily: [
    {
      post_id: 1,
      post_title: "오늘 날씨 왜 이렇게 추움?",
      author: "익명러",
      tag: TAGS[1],
      anonymity: true,
      like_count: 4,
      comment_count: 2,
      create_time: "2025-11-24T09:00:00Z",
      contents: "아침에 나갔다가 동상 걸리는 줄;; 패딩 꺼냄.",
      comments: [
        makeComment(1, "감자튀김", "서울도 완전 겨울임 ㅋㅋ", true),
        makeComment(2, "따뜻한방", "갑자기 너무 추워졌더라…"),
      ],
    },
    {
      post_id: 2,
      post_title: "요즘 뭐하고 지내냐",
      author: "코딩러",
      tag: TAGS[1],
      anonymity: false,
      like_count: 1,
      comment_count: 0,
      create_time: "2025-11-23T15:30:00Z",
      contents: "학교 끝나면 그냥 침대에 눕고 끝나는 듯",
      comments: [],
    },
    {
      post_id: 3,
      post_title: "강아지 산책시키다가 생긴 일",
      author: "익명",
      tag: TAGS[1],
      anonymity: true,
      like_count: 2,
      comment_count: 1,
      create_time: "2025-11-22T11:10:00Z",
      contents: "갑자기 뛰어서 따라가느라 죽을 뻔함...",
      comments: [makeComment(1, "멍멍이", "강아지는 뛰는 게 국룰 ㅋㅋ")],
    },
  ],

  lecture: [
    {
      post_id: 4,
      post_title: "운영체제 강의 너무 어려운 사람?",
      author: "홍길동",
      tag: TAGS[2],
      anonymity: false,
      like_count: 6,
      comment_count: 2,
      create_time: "2025-11-21T13:00:00Z",
      contents: "프로세스 스케줄링부터 멘붕 옴…",
      comments: [
        makeComment(1, "메모리박살", "공감… CPU 스케줄링 머리 아픔"),
        makeComment(2, "익명", "나도 수업 들으면서 반은 놓침;;", true),
      ],
    },
    {
      post_id: 5,
      post_title: "DB 과제 팁 공유",
      author: "익명",
      tag: TAGS[2],
      anonymity: true,
      like_count: 2,
      comment_count: 0,
      create_time: "2025-11-20T10:20:00Z",
      contents: "JOIN 잘 쓰면 반은 해결됨 ㄹㅇ",
      comments: [],
    },
    {
      post_id: 6,
      post_title: "웹프 수업에서 리액트 가르치냐?",
      author: "코더맨",
      tag: TAGS[2],
      anonymity: false,
      like_count: 1,
      comment_count: 1,
      create_time: "2025-11-18T17:00:00Z",
      contents: "리액트 안 알려주면 내가 따로 공부해야겠네 ㅋㅋ",
      comments: [makeComment(1, "JS덕후", "리액트는 무조건 알아야지!")],
    },
  ],

  promotion: [
    {
      post_id: 7,
      post_title: "스터디 그룹 모집합니다!",
      author: "스터디장",
      tag: TAGS[3],
      anonymity: false,
      like_count: 9,
      comment_count: 2,
      create_time: "2025-11-22T21:00:00Z",
      contents: "백준 골드 목표 스터디 모집!",
      comments: [
        makeComment(1, "참여희망", "저 신청합니다!"),
        makeComment(2, "익명", "시간대가 어떻게 되나요?", true),
      ],
    },
    {
      post_id: 8,
      post_title: "중고 노트북 팝니다",
      author: "장터user",
      tag: TAGS[3],
      anonymity: false,
      like_count: 3,
      comment_count: 0,
      create_time: "2025-11-20T08:10:00Z",
      contents: "맥북 2020년형, 상태 좋음!",
      comments: [],
    },
    {
      post_id: 9,
      post_title: "헬스장 신규 멤버 모집 공지",
      author: "헬스장장",
      tag: TAGS[3],
      anonymity: false,
      like_count: 1,
      comment_count: 1,
      create_time: "2025-11-19T14:30:00Z",
      contents: "오늘 등록하면 30% 할인!",
      comments: [makeComment(1, "헬스중", "할인 좋네요")],
    },
  ],

  typo: [
    {
      post_id: 10,
      post_title: "이 문장 띄어쓰기 좀 봐주라 ㅋㅋ",
      author: "맞춤법러",
      tag: TAGS[4],
      anonymity: false,
      like_count: 5,
      comment_count: 1,
      create_time: "2025-11-23T13:00:00Z",
      contents: "안녕 하세요 저는 오늘 밥 을 먹 었 습니다.",
      comments: [makeComment(1, "문법헌터", "ㅋㅋㅋㅋㅋ 너 일부러 그랬지")],
    },
    {
      post_id: 11,
      post_title: "오타 발견한 사람?",
      author: "익명",
      tag: TAGS[4],
      anonymity: true,
      like_count: 1,
      comment_count: 0,
      create_time: "2025-11-21T11:10:00Z",
      contents: "레포트에 '진리'가 '찐리'로 되어 있었음...",
      comments: [],
    },
    {
      post_id: 12,
      post_title: "콘솔 찍다가 오타―... 망했다",
      author: "홍길동",
      tag: TAGS[4],
      anonymity: false,
      like_count: 3,
      comment_count: 1,
      create_time: "2025-11-19T07:40:00Z",
      contents: "console.logg() 때문에 1시간 날림 ㅋㅋㅋㅋ",
      comments: [makeComment(1, "자바스크립트싫다", "ㅋㅋㅋ 공감한다")],
    },
  ],
};
