// src/api/dummy/board_dummy.ts

import type { BoardContent, BoardComment } from "../../screens/board/BoardList";

function makeComment(
  id: number,
  author: string,
  content: string,
  anonymity?: boolean
): BoardComment {
  return {
    id,
    author,
    contents: content,
    anonymity: anonymity ?? false,
    create_time: new Date().toISOString(),
  };
}

export const BOARD_DUMMY: Record<string, BoardContent[]> = {
  free: [
    {
      post_id: 1,
      post_title: "오늘 날씨 미쳤다;;",
      author: "익명",
      tag: "잡담",
      anonymity: true,
      like_count: 3,
      comment_count: 2,
      create_time: "2025-11-10T09:00:00Z",
      contents: "진짜 너무 춥다.. 패딩 꺼냄.",
      comments: [
        makeComment(1, "감자튀김", "서울도 개추움", true),
        makeComment(2, "코딩러", "갑자기 왜 이렇게 변했지 ㅋㅋ"),
      ],
    },
    {
      post_id: 2,
      post_title: "요즘 헬스 꾸준히 하는 사람 있어?",
      author: "홍길동",
      tag: "운동",
      anonymity: false,
      like_count: 5,
      comment_count: 1,
      create_time: "2025-11-09T12:00:00Z",
      contents: "3대 300 목표로 하고 있는데 조언좀...",
      comments: [makeComment(1, "프로틴러", "일단 꾸준히 하는 게 제일임")],
    },
    {
      post_id: 3,
      post_title: "넷플 뭐 볼까 추천좀",
      author: "익명",
      tag: "추천",
      anonymity: true,
      like_count: 1,
      comment_count: 0,
      create_time: "2025-11-07T18:00:00Z",
      contents: "공포, 스릴러 좋아함!",
      comments: [],
    },
    {
      post_id: 4,
      post_title: "요즘 학교에서 개강총회 함?",
      author: "대학생",
      tag: "학교",
      anonymity: false,
      like_count: 2,
      comment_count: 1,
      create_time: "2025-11-07T09:00:00Z",
      contents: "우리학교는 그냥 온라인으로 함...",
      comments: [makeComment(1, "교수님", "요즘 온라인이 대세지")],
    },
    {
      post_id: 5,
      post_title: "개발자 노트북 추천좀",
      author: "코린이",
      tag: "IT",
      anonymity: false,
      like_count: 7,
      comment_count: 3,
      create_time: "2025-11-05T13:00:00Z",
      contents: "맥북이 좋을까? 갤북이 좋을까?",
      comments: [
        makeComment(1, "맥북유저", "맥북 사셈"),
        makeComment(2, "윈도우러", "VSCode 쓸거면 윈도우도 좋아요"),
        makeComment(3, "전자기기덕후", "예산 알려줘야 추천 가능함"),
      ],
    },
  ],

  discussion: [
    {
      post_id: 101,
      post_title: "프론트는 리액트가 미래가 맞나?",
      author: "FE초보",
      tag: "토론",
      anonymity: false,
      like_count: 10,
      comment_count: 3,
      create_time: "2025-10-10T09:30:00Z",
      contents: "솔직히 Vue도 좋은데.. 리액트가 너무 대세긴 해.",
      comments: [
        makeComment(1, "리액트신봉자", "리액트는 대세임"),
        makeComment(2, "뷰유저", "Vue도 좋아요 ㅠㅠ"),
        makeComment(3, "Svelte유저", "스벨트는요..."),
      ],
    },
    {
      post_id: 102,
      post_title: "AI로 개발자 사라질까?",
      author: "익명",
      tag: "AI",
      anonymity: true,
      like_count: 4,
      comment_count: 0,
      create_time: "2025-10-08T11:00:00Z",
      contents: "진짜로 걱정됨...",
      comments: [],
    },
    {
      post_id: 103,
      post_title: "문과 vs 이과 여전히 의미 있나?",
      author: "학생A",
      tag: "교육",
      anonymity: true,
      like_count: 2,
      comment_count: 1,
      create_time: "2025-10-06T16:00:00Z",
      contents: "요즘은 전공보다 포트폴리오 시대 아닌가?",
      comments: [makeComment(1, "취준러", "맞는 말인 듯...")],
    },
    {
      post_id: 104,
      post_title: "GDP가 성장해도 체감이 안 되는 이유는?",
      author: "경제인",
      tag: "경제",
      anonymity: false,
      like_count: 3,
      comment_count: 0,
      create_time: "2025-10-05T14:00:00Z",
      contents: "실질소득, 물가, 분배구조가 문제라는 의견 많음.",
      comments: [],
    },
    {
      post_id: 105,
      post_title: "과연 우주여행은 언제 가능할까?",
      author: "우주덕후",
      tag: "과학",
      anonymity: false,
      like_count: 6,
      comment_count: 2,
      create_time: "2025-10-02T08:30:00Z",
      contents: "일론이 하면 언젠간 되겠지 뭐...",
      comments: [
        makeComment(1, "NASA", "생각보다 먼 미래임"),
        makeComment(2, "스페이스엑스", "이미 테스트 중~"),
      ],
    },
  ],

  qna: [
    {
      post_id: 201,
      post_title: "React Query 캐시 무한 로딩 버그 질문",
      author: "FE초보",
      tag: "리액트",
      anonymity: false,
      like_count: 1,
      comment_count: 1,
      create_time: "2025-11-14T15:00:00Z",
      contents: "캐시가 갱신이 안 되고 무한 로딩 중입니다. 어떻게 해결할까요?",
      comments: [makeComment(1, "경험자", "queryKey 의존성 다시 확인해보셈")],
    },
    {
      post_id: 202,
      post_title: "Docker 안에서 gdb 디버깅이 안 돼요",
      author: "CS학생",
      tag: "Docker",
      anonymity: false,
      like_count: 0,
      comment_count: 0,
      create_time: "2025-11-13T11:00:00Z",
      contents: "ptrace 권한 문제 같은데 해결법 있을까요?",
      comments: [],
    },
    {
      post_id: 203,
      post_title: "Java에서 NullPointerException 방지팁?",
      author: "백엔드초보",
      tag: "Java",
      anonymity: false,
      like_count: 3,
      comment_count: 2,
      create_time: "2025-11-10T17:00:00Z",
      contents: "Optional을 쓰면 해결된다고 하는데, 실제로 어떤 패턴을 쓰나요?",
      comments: [
        makeComment(1, "오라클덕후", "Optional 남발은 비추"),
        makeComment(2, "백엔드시니어", "NPE 안 나는 코드 구조 짜는 게 제일임"),
      ],
    },
    {
      post_id: 204,
      post_title: "C# WPF 바인딩 오류 도와주세요",
      author: "C샵맨",
      tag: "C#",
      anonymity: false,
      like_count: 2,
      comment_count: 3,
      create_time: "2025-11-05T09:00:00Z",
      contents: "BindingExpression path 오류가 뜹니다. 원인 알 수 있을까요?",
      comments: [
        makeComment(1, "WPF전문가", "DataContext 확인하세요"),
        makeComment(2, "기타", "ViewModel 연결 문제일 확률 큼"),
        makeComment(3, "조언가", "x:Name 제대로 확인했나요?"),
      ],
    },
    {
      post_id: 205,
      post_title: "Python에서 리스트 깊은 복사?",
      author: "파이썬러",
      tag: "Python",
      anonymity: false,
      like_count: 0,
      comment_count: 1,
      create_time: "2025-11-01T21:00:00Z",
      contents: "copy()랑 deepcopy() 정확한 차이가 뭔가요?",
      comments: [
        makeComment(1, "파이썬고인물", "mutable vs immutable 차이 때문", true),
      ],
    },
  ],
};
