import type { IProblem, FetchProblemParams } from "../problem_api";

const DUMMY_STORE: Record<string, IProblem> = {
  "1": {
    id: 1,
    title: "두 수의 합",
    difficulty: "하",
    views: 387,
    uploadDate: "2025-07-02",
    author: "알고위자드",
    solvedCount: 77,
    successRate: "92%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "두 개의 정수 A와 B를 입력받아 A+B를 출력한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "1 2",
        output: "3",
      },
      {
        input: "5 7",
        output: "12",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["구현", "기초"],
  },
  "2": {
    id: 2,
    title: "정렬된 배열에서 원소 찾기",
    difficulty: "중",
    views: 174,
    uploadDate: "2025-07-03",
    author: "Ara",
    solvedCount: 91,
    successRate: "32%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description:
      "오름차순 정렬된 배열에서 값 X의 존재 여부를 이진 탐색으로 판별한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 2",
        output: "예시 출력 2",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "0%",
    tags: ["이진 탐색", "탐색", "기초 알고리즘"],
  },
  "3": {
    id: 3,
    title: "가장 긴 팰린드롬",
    difficulty: "상",
    views: 276,
    uploadDate: "2025-07-04",
    author: "알고위자드",
    solvedCount: 36,
    successRate: "83%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "문자열 S에서 가장 긴 팰린드롬 부분 문자열의 길이를 구한다.",
    inputDescription: "길이 N의 문자열 S가 주어진다.",
    outputDescription: "최장 팰린드롬 부분 문자열의 길이를 출력한다.",
    examples: [
      {
        input: "abba",
        output: "4",
      },
      {
        input: "abc",
        output: "1",
      },
    ],
    hint: "중심 확장 또는 Manacher 알고리즘을 고려하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["문자열", "투 포인터", "중심 확장"],
  },
  "4": {
    id: 4,
    title: "스택 수열",
    difficulty: "하",
    views: 318,
    uploadDate: "2025-07-05",
    author: "알고위자드",
    solvedCount: 328,
    successRate: "98%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description:
      "1..N을 스택에 push/pop하여 주어진 수열을 만들 수 있는지 판별한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 4",
        output: "예시 출력 4",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["스택", "시뮬레이션", "자료구조"],
  },
  "5": {
    id: 5,
    title: "괄호의 유효성 검사",
    difficulty: "중",
    views: 426,
    uploadDate: "2025-07-06",
    author: "Yeon",
    solvedCount: 352,
    successRate: "66%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "주어진 괄호 문자열이 올바른지 판별한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 5",
        output: "예시 출력 5",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "0%",
    tags: ["스택", "문자열", "기초"],
  },
  "6": {
    id: 6,
    title: "프린터 큐",
    difficulty: "상",
    views: 361,
    uploadDate: "2025-07-07",
    author: "세이지",
    solvedCount: 162,
    successRate: "99%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description:
      "우선순위 프린터 큐에서 특정 문서가 몇 번째에 출력되는지 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 6",
        output: "예시 출력 6",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["큐", "시뮬레이션", "자료구조"],
  },
  "7": {
    id: 7,
    title: "DFS와 BFS",
    difficulty: "하",
    views: 234,
    uploadDate: "2025-07-08",
    author: "운영자",
    solvedCount: 162,
    successRate: "80%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "그래프에서 DFS와 BFS 방문 순서를 출력한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 7",
        output: "예시 출력 7",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["그래프", "BFS", "DFS"],
  },
  "8": {
    id: 8,
    title: "연속 부분합",
    difficulty: "중",
    views: 112,
    uploadDate: "2025-07-09",
    author: "Ara",
    solvedCount: 67,
    successRate: "40%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "정수 배열에서 연속 부분합의 최댓값을 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 8",
        output: "예시 출력 8",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "50%",
    tags: ["다이나믹 프로그래밍", "카데인", "배열"],
  },
  "9": {
    id: 9,
    title: "회의실 배정",
    difficulty: "상",
    views: 195,
    uploadDate: "2025-07-10",
    author: "gamppe",
    solvedCount: 42,
    successRate: "18%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "회의의 시작/끝 시간이 주어질 때 최대 회의 수를 배정한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 9",
        output: "예시 출력 9",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["그리디", "정렬", "간단"],
  },
  "10": {
    id: 10,
    title: "보석 도둑",
    difficulty: "하",
    views: 253,
    uploadDate: "2025-07-11",
    author: "Ara",
    solvedCount: 60,
    successRate: "29%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "무게 제한이 있는 가방에 보석의 가치를 최대로 담는다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 10",
        output: "예시 출력 10",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["그리디", "정렬", "우선순위 큐"],
  },
  "11": {
    id: 11,
    title: "최단 경로",
    difficulty: "중",
    views: 245,
    uploadDate: "2025-07-12",
    author: "코린이",
    solvedCount: 315,
    successRate: "86%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "가중치 양수 그래프에서 시작점으로부터 최단 거리를 구한다.",
    inputDescription:
      "정점 수 V, 간선 수 E, 시작 정점 K와 E개의 간선(u,v,w)이 주어진다.",
    outputDescription:
      "시작점으로부터 각 정점까지의 최단 거리(도달 불가 시 INF)를 출력한다.",
    examples: [
      {
        input: "5 6 1\n1 2 2\n1 3 5\n2 3 1\n2 4 2\n3 5 1\n4 5 3",
        output: "0 2 3 4 4",
      },
    ],
    hint: "우선순위 큐를 활용하고 방문 확정 시점에 주의하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "0%",
    tags: ["다익스트라", "그래프", "우선순위 큐"],
  },
  "12": {
    id: 12,
    title: "미로 탐색",
    difficulty: "상",
    views: 100,
    uploadDate: "2025-07-13",
    author: "Yeon",
    solvedCount: 139,
    successRate: "84%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "미로에서 시작점에서 도착점까지의 최단 거리를 구한다.",
    inputDescription: "N과 오름차순 정렬된 수열, 그리고 찾을 값 X가 주어진다.",
    outputDescription: "X가 존재하면 1, 없으면 0을 출력한다.",
    examples: [
      {
        input: "5\n1 3 5 7 9\n7",
        output: "1",
      },
      {
        input: "5\n2 4 6 8 10\n3",
        output: "0",
      },
    ],
    hint: "이진 탐색의 중간값 갱신과 경계 조건에 유의하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["BFS", "그래프", "맵 탐색"],
  },
  "13": {
    id: 13,
    title: "N-Queen",
    difficulty: "하",
    views: 385,
    uploadDate: "2025-07-14",
    author: "운영자",
    solvedCount: 206,
    successRate: "83%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "N×N 체스판에 서로 공격하지 않도록 퀸 N개를 배치한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 13",
        output: "예시 출력 13",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["백트래킹", "완전탐색"],
  },
  "14": {
    id: 14,
    title: "부분 수열의 합",
    difficulty: "중",
    views: 167,
    uploadDate: "2025-07-15",
    author: "Minsu",
    solvedCount: 363,
    successRate: "84%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "배열의 부분 수열 중 특정 합을 만드는 경우의 수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 14",
        output: "예시 출력 14",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "33%",
    tags: ["백트래킹", "비트마스크"],
  },
  "15": {
    id: 15,
    title: "동전 1",
    difficulty: "상",
    views: 433,
    uploadDate: "2025-07-16",
    author: "코린이",
    solvedCount: 145,
    successRate: "77%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "동전 종류가 주어졌을 때 합을 만드는 방법의 수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 15",
        output: "예시 출력 15",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["다이나믹 프로그래밍", "조합론"],
  },
  "16": {
    id: 16,
    title: "동전 2",
    difficulty: "하",
    views: 387,
    uploadDate: "2025-07-17",
    author: "운영자",
    solvedCount: 372,
    successRate: "72%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "동전으로 특정 합을 만들 때 최소 동전 개수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 16",
        output: "예시 출력 16",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["다이나믹 프로그래밍", "최적화"],
  },
  "17": {
    id: 17,
    title: "0-1 배낭",
    difficulty: "중",
    views: 491,
    uploadDate: "2025-07-18",
    author: "코린이",
    solvedCount: 48,
    successRate: "45%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description:
      "무게와 가치가 주어진 물건들을 0-1 배낭에 담아 최대 가치를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 17",
        output: "예시 출력 17",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "50%",
    tags: ["다이나믹 프로그래밍", "배낭문제"],
  },
  "18": {
    id: 18,
    title: "LCS (최장 공통 부분수열)",
    difficulty: "상",
    views: 93,
    uploadDate: "2025-07-19",
    author: "Yeon",
    solvedCount: 128,
    successRate: "46%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "두 문자열의 최장 공통 부분수열 길이를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 18",
        output: "예시 출력 18",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["다이나믹 프로그래밍", "문자열"],
  },
  "19": {
    id: 19,
    title: "LIS (최장 증가 부분수열)",
    difficulty: "하",
    views: 262,
    uploadDate: "2025-07-20",
    author: "코린이",
    solvedCount: 349,
    successRate: "74%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "배열에서 가장 긴 증가 부분수열 길이를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 19",
        output: "예시 출력 19",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["다이나믹 프로그래밍", "이진 탐색"],
  },
  "20": {
    id: 20,
    title: "트리의 지름",
    difficulty: "중",
    views: 131,
    uploadDate: "2025-07-21",
    author: "Ara",
    solvedCount: 146,
    successRate: "43%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "트리에서 두 노드 사이의 최장 거리를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 20",
        output: "예시 출력 20",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "66%",
    tags: ["트리", "DFS", "BFS"],
  },
  "21": {
    id: 21,
    title: "유니온 파인드",
    difficulty: "상",
    views: 279,
    uploadDate: "2025-07-22",
    author: "토보",
    solvedCount: 318,
    successRate: "75%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "집합의 합치기/찾기를 처리한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 21",
        output: "예시 출력 21",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["자료구조", "Disjoint Set"],
  },
  "22": {
    id: 22,
    title: "위상 정렬",
    difficulty: "하",
    views: 320,
    uploadDate: "2025-07-23",
    author: "gamppe",
    solvedCount: 272,
    successRate: "92%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "DAG에서 위상 순서를 출력한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 22",
        output: "예시 출력 22",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["그래프", "위상정렬", "큐"],
  },
  "23": {
    id: 23,
    title: "섬의 개수",
    difficulty: "중",
    views: 138,
    uploadDate: "2025-07-24",
    author: "세이지",
    solvedCount: 341,
    successRate: "89%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "지도에서 섬의 개수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 23",
        output: "예시 출력 23",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "0%",
    tags: ["DFS", "BFS", "그래프"],
  },
  "24": {
    id: 24,
    title: "토마토",
    difficulty: "상",
    views: 255,
    uploadDate: "2025-07-25",
    author: "Minsu",
    solvedCount: 325,
    successRate: "73%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "익은 토마토가 퍼지는 최소 일수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 24",
        output: "예시 출력 24",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["BFS", "그래프", "시뮬레이션"],
  },
  "25": {
    id: 25,
    title: "스패닝 트리 (크루스칼)",
    difficulty: "하",
    views: 500,
    uploadDate: "2025-07-26",
    author: "Minsu",
    solvedCount: 25,
    successRate: "12%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "최소 스패닝 트리를 구성한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 25",
        output: "예시 출력 25",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["크루스칼", "그리디", "유니온파인드"],
  },
  "26": {
    id: 26,
    title: "스패닝 트리 (프림)",
    difficulty: "중",
    views: 444,
    uploadDate: "2025-07-27",
    author: "세이지",
    solvedCount: 156,
    successRate: "44%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "우선순위 큐를 이용해 최소 스패닝 트리를 구성한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 26",
        output: "예시 출력 26",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["프림", "그리디", "우선순위 큐"],
  },
  "27": {
    id: 27,
    title: "회전하는 큐",
    difficulty: "상",
    views: 140,
    uploadDate: "2025-07-28",
    author: "토보",
    solvedCount: 252,
    successRate: "100%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description:
      "Deque 회전 연산으로 목표 값들을 꺼낼 때 최소 이동 횟수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 27",
        output: "예시 출력 27",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["덱", "시뮬레이션"],
  },
  "28": {
    id: 28,
    title: "문자열 폭발",
    difficulty: "하",
    views: 319,
    uploadDate: "2025-07-29",
    author: "Minsu",
    solvedCount: 74,
    successRate: "31%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description:
      "문자열에서 특정 패턴이 등장하면 제거하며 최종 문자열을 출력한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 28",
        output: "예시 출력 28",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["문자열", "스택"],
  },
  "29": {
    id: 29,
    title: "부분 문자열 검색 (KMP)",
    difficulty: "중",
    views: 371,
    uploadDate: "2025-07-30",
    author: "Ara",
    solvedCount: 121,
    successRate: "75%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "텍스트에서 패턴이 등장하는 모든 시작 위치를 찾는다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 29",
        output: "예시 출력 29",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "0%",
    tags: ["문자열", "KMP"],
  },
  "30": {
    id: 30,
    title: "Aho-Corasick 다중 패턴",
    difficulty: "상",
    views: 225,
    uploadDate: "2025-07-31",
    author: "코린이",
    solvedCount: 270,
    successRate: "98%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "여러 패턴의 등장 횟수를 동시에 찾는다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 30",
        output: "예시 출력 30",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["문자열", "트라이", "AC 오토마톤"],
  },
  "31": {
    id: 31,
    title: "트라이 (사전 저장)",
    difficulty: "하",
    views: 182,
    uploadDate: "2025-08-01",
    author: "gamppe",
    solvedCount: 49,
    successRate: "44%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "문자열 집합을 트라이로 저장하고 탐색한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 31",
        output: "예시 출력 31",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["자료구조", "트라이"],
  },
  "32": {
    id: 32,
    title: "BIT (펜윅 트리)",
    difficulty: "중",
    views: 103,
    uploadDate: "2025-08-02",
    author: "토보",
    solvedCount: 394,
    successRate: "76%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "구간 합과 점 업데이트를 처리한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 32",
        output: "예시 출력 32",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "33%",
    tags: ["자료구조", "펜윅 트리"],
  },
  "33": {
    id: 33,
    title: "세그먼트 트리",
    difficulty: "상",
    views: 397,
    uploadDate: "2025-08-03",
    author: "Minsu",
    solvedCount: 263,
    successRate: "65%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "구간 최소/최대/합 질의를 처리한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 33",
        output: "예시 출력 33",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["자료구조", "세그먼트 트리"],
  },
  "34": {
    id: 34,
    title: "오프라인 쿼리 (Mo's)",
    difficulty: "하",
    views: 370,
    uploadDate: "2025-08-04",
    author: "알고위자드",
    solvedCount: 236,
    successRate: "81%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "배열 구간 질의들을 Mo's 알고리즘으로 처리한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 34",
        output: "예시 출력 34",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["알고리즘", "오프라인 쿼리"],
  },
  "35": {
    id: 35,
    title: "두 포인터 - 수의 합",
    difficulty: "중",
    views: 425,
    uploadDate: "2025-08-05",
    author: "Yeon",
    solvedCount: 179,
    successRate: "63%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "정렬된 배열에서 두 수의 합이 목표와 같은 쌍을 찾는다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 35",
        output: "예시 출력 35",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["투 포인터", "정렬"],
  },
  "36": {
    id: 36,
    title: "수열 편집 (에디터)",
    difficulty: "상",
    views: 121,
    uploadDate: "2025-08-06",
    author: "율무",
    solvedCount: 146,
    successRate: "71%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "문서 에디터 명령을 처리한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 36",
        output: "예시 출력 36",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["연결리스트", "스택", "문자열"],
  },
  "37": {
    id: 37,
    title: "덱으로 구현하는 큐",
    difficulty: "하",
    views: 361,
    uploadDate: "2025-08-07",
    author: "알고위자드",
    solvedCount: 303,
    successRate: "83%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "두 스택/덱으로 큐를 구현한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 37",
        output: "예시 출력 37",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["자료구조", "덱", "스택"],
  },
  "38": {
    id: 38,
    title: "버블 소트 카운트",
    difficulty: "중",
    views: 63,
    uploadDate: "2025-08-08",
    author: "율무",
    solvedCount: 56,
    successRate: "23%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "버블 소트 시 swap 횟수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 38",
        output: "예시 출력 38",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "0%",
    tags: ["정렬", "투 포인터"],
  },
  "39": {
    id: 39,
    title: "좌표 압축",
    difficulty: "상",
    views: 500,
    uploadDate: "2025-08-09",
    author: "코린이",
    solvedCount: 189,
    successRate: "91%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "큰 좌표값을 상대 순서로 압축한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 39",
        output: "예시 출력 39",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["정렬", "맵핑"],
  },
  "40": {
    id: 40,
    title: "수 찾기",
    difficulty: "하",
    views: 402,
    uploadDate: "2025-08-10",
    author: "토보",
    solvedCount: 268,
    successRate: "83%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "배열에 특정 수가 존재하는지 빠르게 판별한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 40",
        output: "예시 출력 40",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["이분 탐색", "정렬"],
  },
  "41": {
    id: 41,
    title: "문자열 압축",
    difficulty: "중",
    views: 430,
    uploadDate: "2025-08-11",
    author: "세이지",
    solvedCount: 312,
    successRate: "67%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "연속된 문자 묶음으로 문자열을 압축하여 길이를 줄인다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 41",
        output: "예시 출력 41",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["문자열", "구현"],
  },
  "42": {
    id: 42,
    title: "괄호 추가하기",
    difficulty: "상",
    views: 157,
    uploadDate: "2025-08-12",
    author: "세이지",
    solvedCount: 68,
    successRate: "73%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "연산자 우선순위/괄호 배치로 식의 최댓값을 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 42",
        output: "예시 출력 42",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["브루트포스", "백트래킹"],
  },
  "43": {
    id: 43,
    title: "연속된 수의 합",
    difficulty: "하",
    views: 270,
    uploadDate: "2025-08-13",
    author: "gamppe",
    solvedCount: 259,
    successRate: "58%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "자연수 연속합으로 N을 표현하는 방법의 수를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 43",
        output: "예시 출력 43",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["수학", "투 포인터"],
  },
  "44": {
    id: 44,
    title: "행렬 곱셈 순서",
    difficulty: "중",
    views: 91,
    uploadDate: "2025-08-14",
    author: "알고위자드",
    solvedCount: 226,
    successRate: "54%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "행렬 곱 연산 횟수가 최소가 되도록 순서를 정한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 44",
        output: "예시 출력 44",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "0%",
    tags: ["다이나믹 프로그래밍", "행렬"],
  },
  "45": {
    id: 45,
    title: "플로이드-워셜",
    difficulty: "상",
    views: 157,
    uploadDate: "2025-08-15",
    author: "토보",
    solvedCount: 294,
    successRate: "72%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "모든 쌍 최단 경로를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 45",
        output: "예시 출력 45",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["그래프", "DP"],
  },
  "46": {
    id: 46,
    title: "벨만-포드",
    difficulty: "하",
    views: 202,
    uploadDate: "2025-08-16",
    author: "Yeon",
    solvedCount: 256,
    successRate: "80%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "음수 간선이 있는 그래프의 최단 경로와 음수 사이클 검출.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 46",
        output: "예시 출력 46",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["그래프", "DP"],
  },
  "47": {
    id: 47,
    title: "최소 공통 조상 (LCA)",
    difficulty: "중",
    views: 473,
    uploadDate: "2025-08-17",
    author: "gamppe",
    solvedCount: 301,
    successRate: "92%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "트리에서 두 노드의 LCA를 찾는다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 47",
        output: "예시 출력 47",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "0%",
    tags: ["트리", "이진 리프팅"],
  },
  "48": {
    id: 48,
    title: "이진 검색 트리 검증",
    difficulty: "상",
    views: 445,
    uploadDate: "2025-08-18",
    author: "Yeon",
    solvedCount: 141,
    successRate: "77%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "주어진 트리가 BST인지 검증한다.",
    inputDescription: "N과 오름차순 정렬된 수열, 그리고 찾을 값 X가 주어진다.",
    outputDescription: "X가 존재하면 1, 없으면 0을 출력한다.",
    examples: [
      {
        input: "5\n1 3 5 7 9\n7",
        output: "1",
      },
      {
        input: "5\n2 4 6 8 10\n3",
        output: "0",
      },
    ],
    hint: "이진 탐색의 중간값 갱신과 경계 조건에 유의하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["트리", "재귀"],
  },
  "49": {
    id: 49,
    title: "히스토그램에서 가장 큰 직사각형",
    difficulty: "하",
    views: 169,
    uploadDate: "2025-08-19",
    author: "세이지",
    solvedCount: 225,
    successRate: "93%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "히스토그램에서 가장 큰 직사각형의 넓이를 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 49",
        output: "예시 출력 49",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["스택", "분할정복"],
  },
  "50": {
    id: 50,
    title: "원형 큐 시뮬레이션",
    difficulty: "중",
    views: 61,
    uploadDate: "2025-08-20",
    author: "Minsu",
    solvedCount: 219,
    successRate: "76%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "원형 큐에서 삽입/삭제/회전을 시뮬레이션한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 50",
        output: "예시 출력 50",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "50%",
    tags: ["큐", "시뮬레이션"],
  },
  "51": {
    id: 51,
    title: "괄호 회전하기",
    difficulty: "상",
    views: 398,
    uploadDate: "2025-08-21",
    author: "코린이",
    solvedCount: 387,
    successRate: "75%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "문자열을 회전하여 올바른 괄호 문자열이 되는 경우의 수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 51",
        output: "예시 출력 51",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["문자열", "스택"],
  },
  "52": {
    id: 52,
    title: "팰린드롬 분할",
    difficulty: "하",
    views: 171,
    uploadDate: "2025-08-22",
    author: "율무",
    solvedCount: 49,
    successRate: "24%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "문자열을 팰린드롬 조각들로 나눌 때 최소 분할 수.",
    inputDescription: "길이 N의 문자열 S가 주어진다.",
    outputDescription: "최장 팰린드롬 부분 문자열의 길이를 출력한다.",
    examples: [
      {
        input: "abba",
        output: "4",
      },
      {
        input: "abc",
        output: "1",
      },
    ],
    hint: "중심 확장 또는 Manacher 알고리즘을 고려하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["DP", "문자열"],
  },
  "53": {
    id: 53,
    title: "암호 만들기",
    difficulty: "중",
    views: 442,
    uploadDate: "2025-08-23",
    author: "Minsu",
    solvedCount: 180,
    successRate: "92%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "주어진 문자들로 조건을 만족하는 암호를 생성한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 53",
        output: "예시 출력 53",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["백트래킹", "조합"],
  },
  "54": {
    id: 54,
    title: "토큰 버킷",
    difficulty: "상",
    views: 496,
    uploadDate: "2025-08-24",
    author: "gamppe",
    solvedCount: 291,
    successRate: "87%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "요청이 제한되는 토큰 버킷 시뮬레이션.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 54",
        output: "예시 출력 54",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["시뮬레이션", "큐"],
  },
  "55": {
    id: 55,
    title: "라빈-카프 해싱",
    difficulty: "하",
    views: 495,
    uploadDate: "2025-08-25",
    author: "gamppe",
    solvedCount: 115,
    successRate: "87%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "롤링 해시로 부분 문자열 검색.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 55",
        output: "예시 출력 55",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["문자열", "해싱"],
  },
  "56": {
    id: 56,
    title: "소수 판별",
    difficulty: "중",
    views: 405,
    uploadDate: "2025-08-26",
    author: "Ara",
    solvedCount: 140,
    successRate: "57%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "큰 정수의 소수 여부 판별.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 56",
        output: "예시 출력 56",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "33%",
    tags: ["수학", "에라토스테네스"],
  },
  "57": {
    id: 57,
    title: "골드바흐 파티션",
    difficulty: "상",
    views: 364,
    uploadDate: "2025-08-27",
    author: "Ara",
    solvedCount: 40,
    successRate: "20%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "짝수를 두 소수의 합으로 표현하는 경우의 수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 57",
        output: "예시 출력 57",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["수학", "소수"],
  },
  "58": {
    id: 58,
    title: "최대공약수와 최소공배수",
    difficulty: "하",
    views: 349,
    uploadDate: "2025-08-28",
    author: "알고위자드",
    solvedCount: 287,
    successRate: "78%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "두 수의 GCD/LCM을 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 58",
        output: "예시 출력 58",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["수학", "유클리드"],
  },
  "59": {
    id: 59,
    title: "행성 터널",
    difficulty: "중",
    views: 402,
    uploadDate: "2025-08-29",
    author: "토보",
    solvedCount: 386,
    successRate: "82%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "3D 좌표 행성들을 최소 비용으로 잇는 MST.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 59",
        output: "예시 출력 59",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "50%",
    tags: ["그래프", "MST", "정렬"],
  },
  "60": {
    id: 60,
    title: "RGB 거리",
    difficulty: "상",
    views: 403,
    uploadDate: "2025-08-30",
    author: "gamppe",
    solvedCount: 350,
    successRate: "82%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "인접 집의 색이 다르게 칠하는 최소 비용.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 60",
        output: "예시 출력 60",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["DP", "그리디"],
  },
  "61": {
    id: 61,
    title: "퇴사",
    difficulty: "하",
    views: 64,
    uploadDate: "2025-08-31",
    author: "gamppe",
    solvedCount: 254,
    successRate: "61%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "상담 일정에서 최대 이익을 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 61",
        output: "예시 출력 61",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["DP", "스케줄링"],
  },
  "62": {
    id: 62,
    title: "숫자 카드 2",
    difficulty: "중",
    views: 97,
    uploadDate: "2025-09-01",
    author: "운영자",
    solvedCount: 295,
    successRate: "84%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "카드의 등장 횟수를 빠르게 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 62",
        output: "예시 출력 62",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "0%",
    tags: ["맵", "이분 탐색"],
  },
  "63": {
    id: 63,
    title: "문자열 집합",
    difficulty: "상",
    views: 95,
    uploadDate: "2025-09-02",
    author: "Yeon",
    solvedCount: 145,
    successRate: "60%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "문자열 집합에 포함 여부를 묻는 질의 처리.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 63",
        output: "예시 출력 63",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["자료구조", "트라이", "셋"],
  },
  "64": {
    id: 64,
    title: "아나그램 거리",
    difficulty: "하",
    views: 486,
    uploadDate: "2025-09-03",
    author: "Ara",
    solvedCount: 298,
    successRate: "62%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "두 문자열이 아나그램이 되기 위한 최소 교환/삭제 수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 64",
        output: "예시 출력 64",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["문자열", "해시맵"],
  },
  "65": {
    id: 65,
    title: "빙산",
    difficulty: "중",
    views: 473,
    uploadDate: "2025-09-04",
    author: "gamppe",
    solvedCount: 354,
    successRate: "72%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "빙산이 분리되는 최초의 시간을 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 65",
        output: "예시 출력 65",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "66%",
    tags: ["BFS", "시뮬레이션"],
  },
  "66": {
    id: 66,
    title: "적록색약",
    difficulty: "상",
    views: 128,
    uploadDate: "2025-09-05",
    author: "Minsu",
    solvedCount: 155,
    successRate: "84%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "색상 구분 방식에 따른 영역 개수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 66",
        output: "예시 출력 66",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["DFS", "BFS", "그래프"],
  },
  "67": {
    id: 67,
    title: "택배 배송",
    difficulty: "하",
    views: 139,
    uploadDate: "2025-09-06",
    author: "알고위자드",
    solvedCount: 159,
    successRate: "68%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "도로망에서 최단 경로를 이용한 배송 시간.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 67",
        output: "예시 출력 67",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["다익스트라", "그래프"],
  },
  "68": {
    id: 68,
    title: "연결 요소의 개수",
    difficulty: "중",
    views: 427,
    uploadDate: "2025-09-07",
    author: "코린이",
    solvedCount: 195,
    successRate: "78%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "무방향 그래프의 연결 요소 개수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 68",
        output: "예시 출력 68",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["그래프", "DFS"],
  },
  "69": {
    id: 69,
    title: "특정 거리의 도시 찾기",
    difficulty: "상",
    views: 493,
    uploadDate: "2025-09-08",
    author: "율무",
    solvedCount: 46,
    successRate: "66%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "BFS로 정확히 K만큼 떨어진 도시 찾기.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 69",
        output: "예시 출력 69",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["BFS", "그래프"],
  },
  "70": {
    id: 70,
    title: "카드 정렬하기",
    difficulty: "하",
    views: 61,
    uploadDate: "2025-09-09",
    author: "코린이",
    solvedCount: 190,
    successRate: "49%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "합치는 비용이 최소가 되도록 카드 묶음 합치기.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 70",
        output: "예시 출력 70",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["그리디", "우선순위 큐"],
  },
  "71": {
    id: 71,
    title: "강의실 배정",
    difficulty: "중",
    views: 142,
    uploadDate: "2025-09-10",
    author: "Minsu",
    solvedCount: 399,
    successRate: "77%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "겹치지 않게 강의실 최소 개수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 71",
        output: "예시 출력 71",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["그리디", "우선순위 큐"],
  },
  "72": {
    id: 72,
    title: "문자열 뒤집기",
    difficulty: "상",
    views: 64,
    uploadDate: "2025-09-11",
    author: "율무",
    solvedCount: 77,
    successRate: "80%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "문자열에서 연속된 그룹의 개수 최소로 만들기.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 72",
        output: "예시 출력 72",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["그리디", "문자열"],
  },
  "73": {
    id: 73,
    title: "나무 자르기",
    difficulty: "하",
    views: 487,
    uploadDate: "2025-09-12",
    author: "토보",
    solvedCount: 209,
    successRate: "58%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "절단기 높이를 결정하여 얻는 목재의 길이 최댓값.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 73",
        output: "예시 출력 73",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["이분 탐색", "그리디"],
  },
  "74": {
    id: 74,
    title: "공유기 설치",
    difficulty: "중",
    views: 280,
    uploadDate: "2025-09-13",
    author: "운영자",
    solvedCount: 85,
    successRate: "89%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "집들에 공유기를 설치해 최소 거리의 최댓값.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 74",
        output: "예시 출력 74",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "0%",
    tags: ["이분 탐색", "그리디"],
  },
  "75": {
    id: 75,
    title: "휴게소 세우기",
    difficulty: "상",
    views: 167,
    uploadDate: "2025-09-14",
    author: "Minsu",
    solvedCount: 369,
    successRate: "85%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "추가 휴게소 설치로 구간 최대 간격 최소화.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 75",
        output: "예시 출력 75",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["이분 탐색", "그리디"],
  },
  "76": {
    id: 76,
    title: "도서관",
    difficulty: "하",
    views: 268,
    uploadDate: "2025-09-15",
    author: "알고위자드",
    solvedCount: 337,
    successRate: "63%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "왕복 이동 최소화로 책 옮기기.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 76",
        output: "예시 출력 76",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["그리디", "정렬"],
  },
  "77": {
    id: 77,
    title: "계단 오르기",
    difficulty: "중",
    views: 143,
    uploadDate: "2025-09-16",
    author: "세이지",
    solvedCount: 110,
    successRate: "51%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "연속 3칸 금지 규칙으로 최대 점수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 77",
        output: "예시 출력 77",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["DP", "경로"],
  },
  "78": {
    id: 78,
    title: "포도주 시식",
    difficulty: "상",
    views: 470,
    uploadDate: "2025-09-17",
    author: "토보",
    solvedCount: 362,
    successRate: "65%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "연속 3잔 금지 규칙으로 최대 양.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 78",
        output: "예시 출력 78",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["DP", "경로"],
  },
  "79": {
    id: 79,
    title: "타일 채우기",
    difficulty: "하",
    views: 463,
    uploadDate: "2025-09-18",
    author: "율무",
    solvedCount: 379,
    successRate: "93%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "2×N 타일링 경우의 수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 79",
        output: "예시 출력 79",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["DP", "조합"],
  },
  "80": {
    id: 80,
    title: "가장 긴 공통 접두사",
    difficulty: "중",
    views: 499,
    uploadDate: "2025-09-19",
    author: "코린이",
    solvedCount: 260,
    successRate: "82%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "여러 문자열의 공통 접두사의 길이.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 80",
        output: "예시 출력 80",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "50%",
    tags: ["문자열", "트라이"],
  },
  "81": {
    id: 81,
    title: "불!",
    difficulty: "상",
    views: 480,
    uploadDate: "2025-09-20",
    author: "알고위자드",
    solvedCount: 136,
    successRate: "70%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "불과 사람이 동시에 퍼지는 맵에서 탈출 가능 여부.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 81",
        output: "예시 출력 81",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["BFS", "시뮬레이션"],
  },
  "82": {
    id: 82,
    title: "연구소",
    difficulty: "하",
    views: 264,
    uploadDate: "2025-09-21",
    author: "코린이",
    solvedCount: 188,
    successRate: "72%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "벽 3개를 세워 바이러스 확산을 최소화.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 82",
        output: "예시 출력 82",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["브루트포스", "BFS"],
  },
  "83": {
    id: 83,
    title: "치킨 배달",
    difficulty: "중",
    views: 239,
    uploadDate: "2025-09-22",
    author: "율무",
    solvedCount: 348,
    successRate: "72%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "도시의 치킨 거리 합 최소화.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 83",
        output: "예시 출력 83",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "66%",
    tags: ["브루트포스", "조합"],
  },
  "84": {
    id: 84,
    title: "소가 길을 건너간 이유",
    difficulty: "상",
    views: 119,
    uploadDate: "2025-09-23",
    author: "율무",
    solvedCount: 153,
    successRate: "77%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "소들의 이동 규칙으로 충돌/교차 횟수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 84",
        output: "예시 출력 84",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["시뮬레이션", "구현"],
  },
  "85": {
    id: 85,
    title: "배열 돌리기",
    difficulty: "하",
    views: 115,
    uploadDate: "2025-09-24",
    author: "운영자",
    solvedCount: 325,
    successRate: "74%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "2D 배열을 회전시키는 연산을 수행.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 85",
        output: "예시 출력 85",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["구현", "시뮬레이션"],
  },
  "86": {
    id: 86,
    title: "불우이웃돕기",
    difficulty: "중",
    views: 283,
    uploadDate: "2025-09-25",
    author: "알고위자드",
    solvedCount: 330,
    successRate: "71%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["C", "C++", "Java", "Python"],
    description: "불필요한 간선을 제거하여 MST 비용 절약.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 86",
        output: "예시 출력 86",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["그래프", "MST"],
  },
  "87": {
    id: 87,
    title: "드래곤 커브",
    difficulty: "상",
    views: 190,
    uploadDate: "2025-09-26",
    author: "Minsu",
    solvedCount: 42,
    successRate: "18%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "규칙에 따라 드래곤 커브를 그린 후 정사각형 개수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 87",
        output: "예시 출력 87",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["시뮬레이션", "그래프"],
  },
  "88": {
    id: 88,
    title: "톱니바퀴",
    difficulty: "하",
    views: 472,
    uploadDate: "2025-09-27",
    author: "운영자",
    solvedCount: 295,
    successRate: "62%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "회전 규칙에 따라 톱니 상태 변화를 시뮬레이션.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 88",
        output: "예시 출력 88",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["시뮬레이션", "구현"],
  },
  "89": {
    id: 89,
    title: "추월",
    difficulty: "중",
    views: 280,
    uploadDate: "2025-09-28",
    author: "gamppe",
    solvedCount: 55,
    successRate: "24%",
    timeLimit: "2초",
    memoryLimit: "128MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "터널을 통과하며 추월한 차량의 수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 89",
        output: "예시 출력 89",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "66%",
    tags: ["해시맵", "정렬"],
  },
  "90": {
    id: 90,
    title: "컵라면",
    difficulty: "상",
    views: 428,
    uploadDate: "2025-09-29",
    author: "세이지",
    solvedCount: 173,
    successRate: "57%",
    timeLimit: "3초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "데드라인과 점수가 있는 문제에서 최대 점수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 90",
        output: "예시 출력 90",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["그리디", "우선순위 큐"],
  },
  "91": {
    id: 91,
    title: "반복수열",
    difficulty: "하",
    views: 227,
    uploadDate: "2025-09-30",
    author: "Minsu",
    solvedCount: 226,
    successRate: "55%",
    timeLimit: "1초",
    memoryLimit: "512MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "자릿수 제곱의 합으로 생성되는 수열의 사이클 길이.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 91",
        output: "예시 출력 91",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["수학", "해시셋"],
  },
  "92": {
    id: 92,
    title: "암호코드",
    difficulty: "중",
    views: 125,
    uploadDate: "2025-10-01",
    author: "Ara",
    solvedCount: 118,
    successRate: "52%",
    timeLimit: "2초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "1~26 매핑으로 해석 가능한 문자열의 개수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 92",
        output: "예시 출력 92",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 3,
    userSuccessRate: "33%",
    tags: ["DP", "문자열"],
  },
  "93": {
    id: 93,
    title: "로프",
    difficulty: "상",
    views: 351,
    uploadDate: "2025-10-02",
    author: "코린이",
    solvedCount: 174,
    successRate: "62%",
    timeLimit: "3초",
    memoryLimit: "128MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "로프 병렬 연결로 들 수 있는 최대 중량.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 93",
        output: "예시 출력 93",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 1,
    userSuccessRate: "100%",
    tags: ["그리디", "정렬"],
  },
  "94": {
    id: 94,
    title: "덩치",
    difficulty: "하",
    views: 206,
    uploadDate: "2025-10-03",
    author: "Ara",
    solvedCount: 127,
    successRate: "53%",
    timeLimit: "1초",
    memoryLimit: "256MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "사람들의 덩치를 비교하여 순위를 매긴다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 94",
        output: "예시 출력 94",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["브루트포스", "정렬"],
  },
  "95": {
    id: 95,
    title: "집합",
    difficulty: "중",
    views: 395,
    uploadDate: "2025-10-04",
    author: "알고위자드",
    solvedCount: 184,
    successRate: "60%",
    timeLimit: "2초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "비트마스크로 집합 연산을 처리한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 95",
        output: "예시 출력 95",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 2,
    userSuccessRate: "100%",
    tags: ["비트마스크", "구현"],
  },
  "96": {
    id: 96,
    title: "이항 계수",
    difficulty: "상",
    views: 321,
    uploadDate: "2025-10-05",
    author: "gamppe",
    solvedCount: 262,
    successRate: "58%",
    timeLimit: "3초",
    memoryLimit: "1024MB",
    allowedLanguages: ["C++", "Java", "Python"],
    description: "조합 nCk 값을 구한다.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 96",
        output: "예시 출력 96",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["수학", "DP"],
  },
  "97": {
    id: 97,
    title: "가르침",
    difficulty: "하",
    views: 205,
    uploadDate: "2025-10-06",
    author: "운영자",
    solvedCount: 283,
    successRate: "62%",
    timeLimit: "1초",
    memoryLimit: "128MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "알파벳 학습으로 읽을 수 있는 단어 최대 개수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 97",
        output: "예시 출력 97",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["백트래킹", "비트마스크"],
  },
  "98": {
    id: 98,
    title: "스티커",
    difficulty: "중",
    views: 107,
    uploadDate: "2025-10-07",
    author: "토보",
    solvedCount: 140,
    successRate: "44%",
    timeLimit: "2초",
    memoryLimit: "256MB",
    allowedLanguages: ["Java", "Python", "C++"],
    description: "2행 스티커에서 인접 규칙 하 최대 점수.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 98",
        output: "예시 출력 98",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "attempted",
    userAttempts: 1,
    userSuccessRate: "0%",
    tags: ["DP", "그리디"],
  },
  "99": {
    id: 99,
    title: "괄호 제거",
    difficulty: "상",
    views: 72,
    uploadDate: "2025-10-08",
    author: "gamppe",
    solvedCount: 43,
    successRate: "40%",
    timeLimit: "3초",
    memoryLimit: "512MB",
    allowedLanguages: ["Python", "C++", "Java"],
    description: "괄호 쌍을 제거해 만들 수 있는 서로 다른 식들.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 99",
        output: "예시 출력 99",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "solved",
    userAttempts: 3,
    userSuccessRate: "100%",
    tags: ["백트래킹", "문자열"],
  },
  "100": {
    id: 100,
    title: "줄 세우기",
    difficulty: "하",
    views: 293,
    uploadDate: "2025-10-09",
    author: "알고위자드",
    solvedCount: 232,
    successRate: "59%",
    timeLimit: "1초",
    memoryLimit: "1024MB",
    allowedLanguages: ["Kotlin", "Java", "Python"],
    description: "키 순서대로 줄 세우기.",
    inputDescription:
      "문제에 맞는 입력 형식이 주어진다. 제약은 문제 설명을 참고하라.",
    outputDescription: "요구된 결과를 출력한다.",
    examples: [
      {
        input: "예시 입력 100",
        output: "예시 출력 100",
      },
    ],
    hint: "해결 전략을 작은 하위 문제로 나누고 경계 조건을 먼저 점검하라.",
    source: "알고리즘 기본/응용",
    userStatus: "none",
    userAttempts: 0,
    userSuccessRate: "0%",
    tags: ["위상정렬", "그래프"],
  },
};

function cmpDifficulty(a: string, b: string) {
  const order = ["하", "중", "상"];
  return order.indexOf(a) - order.indexOf(b);
}

export async function fetchDummyProblems({
  sortType,
  searchTerm,
  isLoggedIn,
  page = 1,
  size = 50,
}: FetchProblemParams): Promise<IProblem[]> {
  let list = Object.values(DUMMY_STORE);

  if (searchTerm && searchTerm.trim().length >= 2) {
    const key = searchTerm.toLowerCase();
    list = list.filter(
      (p) =>
        p.title.toLowerCase().includes(key) || p.id.toString().includes(key)
    );
  }

  switch (sortType) {
    case "latest":
      list.sort((a, b) => b.uploadDate.localeCompare(a.uploadDate));
      break;
    case "low_difficulty":
      list.sort((a, b) => cmpDifficulty(a.difficulty, b.difficulty));
      break;
    case "high_difficulty":
      list.sort((a, b) => cmpDifficulty(b.difficulty, a.difficulty));
      break;
    case "views":
      list.sort((a, b) => b.views - a.views);
      break;
    case "id":
      list.sort((a, b) => a.id - b.id);
      break;
  }

  if (!isLoggedIn) {
    list = list.map((p) => ({ ...p, userStatus: "none" }));
  }

  const start = (page - 1) * size;
  const end = start + size;
  return list.slice(start, end);
}

export async function getDummyProblemDetail(
  problemId: string
): Promise<IProblem> {
  const data = DUMMY_STORE[problemId];
  if (!data) throw new Error("문제를 찾을 수 없습니다.");
  return { ...data };
}

export async function increaseDummyView(problemId: string): Promise<void> {
  if (DUMMY_STORE[problemId]) DUMMY_STORE[problemId].views += 1;
}
